"use client";
import { useState } from "react";
import { defaultContent, PortfolioContent } from "@/lib/portfolio-content";

const input = "w-full rounded border border-emerald-400/30 bg-black/40 px-3 py-2 text-white";
export default function AdminPanel() {
  const [password, setPassword] = useState(""); const [content, setContent] = useState<PortfolioContent>(defaultContent); const [loggedIn, setLoggedIn] = useState(false); const [message, setMessage] = useState("");
  const login = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!r.ok) return setMessage("Incorrect password."); const data = await fetch("/api/admin/content").then(x => x.json()); setContent(data); setLoggedIn(true); setMessage(""); };
  const save = async () => { const r = await fetch("/api/admin/content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); setMessage(r.ok ? "Saved to Supabase." : (await r.json()).error); };
  const addProject = () => setContent(c => ({ ...c, projects: [...c.projects, { id: crypto.randomUUID(), title: "New project", category: "Cybersecurity project", description: "Add details later." }] }));
  const addBlog = () => setContent(c => ({ ...c, blogs: [...c.blogs, { id: crypto.randomUUID(), title: "New blog post", summary: "Short summary", body: "Write your post here.", publishedAt: new Date().toISOString().slice(0, 10) }] }));
  if (!loggedIn) return <main className="min-h-screen bg-[#06110e] px-6 py-28 text-white"><form onSubmit={login} className="mx-auto max-w-md rounded-2xl border border-emerald-400/30 bg-black/50 p-8"><p className="mb-2 text-xs uppercase tracking-[.25em] text-emerald-400">Private area</p><h1 className="mb-6 text-4xl font-bold">Admin login</h1><input className={input} type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)} /><button className="mt-4 w-full rounded bg-emerald-400 px-4 py-3 font-bold text-black">Log in</button>{message && <p className="mt-3 text-red-300">{message}</p>}</form></main>;
  return <main className="min-h-screen bg-[#06110e] px-5 py-20 text-white"><div className="mx-auto max-w-4xl"><p className="text-xs uppercase tracking-[.25em] text-emerald-400">Portfolio control panel</p><h1 className="mb-8 text-4xl font-bold">Edit your website</h1><section className="space-y-3 rounded-2xl border border-emerald-400/30 bg-black/40 p-5"><h2 className="text-2xl font-bold">Section titles & learning</h2><input className={input} value={content.learningTitle} onChange={e=>setContent({...content,learningTitle:e.target.value})} placeholder="Learning section title"/><input className={input} value={content.projectsTitle} onChange={e=>setContent({...content,projectsTitle:e.target.value})} placeholder="Projects section title"/><List label="Certifications" values={content.certifications} onChange={v=>setContent({...content,certifications:v})}/><List label="Topics studied" values={content.topics} onChange={v=>setContent({...content,topics:v})}/></section><Editor title="Projects" items={content.projects} add={addProject} remove={i=>setContent({...content,projects:content.projects.filter((_,n)=>n!==i)})} render={(item,i)=><><input className={input} value={item.title} onChange={e=>setContent({...content,projects:content.projects.map((p,n)=>n===i?{...p,title:e.target.value}:p)})}/><input className={input} value={item.category} onChange={e=>setContent({...content,projects:content.projects.map((p,n)=>n===i?{...p,category:e.target.value}:p)})}/><textarea className={input} value={item.description} onChange={e=>setContent({...content,projects:content.projects.map((p,n)=>n===i?{...p,description:e.target.value}:p)})}/></>}/><Editor title="Blogs" items={content.blogs} add={addBlog} remove={i=>setContent({...content,blogs:content.blogs.filter((_,n)=>n!==i)})} render={(item,i)=><><input className={input} value={item.title} onChange={e=>setContent({...content,blogs:content.blogs.map((p,n)=>n===i?{...p,title:e.target.value}:p)})}/><textarea className={input} value={item.summary} onChange={e=>setContent({...content,blogs:content.blogs.map((p,n)=>n===i?{...p,summary:e.target.value}:p)})}/><textarea className={input} value={item.body} onChange={e=>setContent({...content,blogs:content.blogs.map((p,n)=>n===i?{...p,body:e.target.value}:p)})}/></>}/><button onClick={save} className="mt-8 rounded bg-emerald-400 px-6 py-3 font-bold text-black">Save changes</button>{message&&<p className="mt-3 text-emerald-300">{message}</p>}</div></main>;
}
function List({label,values,onChange}:{label:string;values:string[];onChange:(v:string[])=>void}){return <div><p className="mb-2 font-bold">{label}</p>{values.map((v,i)=><div key={i} className="mb-2 flex gap-2"><input className={input} value={v} onChange={e=>onChange(values.map((x,n)=>n===i?e.target.value:x))}/><button onClick={()=>onChange(values.filter((_,n)=>n!==i))}>Remove</button></div>)}<button onClick={()=>onChange([...values,"New item"])}>+ Add item</button></div>}
function Editor<T>({title,items,add,remove,render}:{title:string;items:T[];add:()=>void;remove:(i:number)=>void;render:(item:T,i:number)=>React.ReactNode}){return <section className="mt-6 rounded-2xl border border-emerald-400/30 bg-black/40 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-bold">{title}</h2><button onClick={add}>+ Add</button></div>{items.map((item,i)=><div key={i} className="mb-4 space-y-2 rounded border border-white/10 p-3">{render(item,i)}<button onClick={()=>remove(i)} className="text-red-300">Remove</button></div>)}</section>}
